[package]
name = "iam-runtime-rs"
version = "0.4.1"
edition = "2021"
description = "Generated client for interacting with iam-runtime services"
license = "Apache-2.0"

[dependencies]
prost = "0.12.4"
prost-types = "0.12.4"
tonic = "0.11"

[build-dependencies]
tonic-build = "0.11.0"
