name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of iam-runtime to generate protobufs for: eg 0.0.0"
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Bump version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v26.1/protoc-26.1-linux-x86_64.zip && \
            unzip protoc-26.1-linux-x86_64.zip && \
            sudo mv bin/protoc /usr/bin/ && \
            sudo mv include/google /usr/include/
          make build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: Generate for v${{ inputs.version }}
          title: Generate for v${{ inputs.version }}
