name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of iam-runtime to generate protobufs for: eg 0.0.0"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Bump version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          make build
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: Generate for v${{ inputs.version }}
          title: Generate for v${{ inputs.version }}

